
# -*- RESTCLIENT -*-
##

##
POST http://localhost:8082/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTQxMzI1OTUsInVzZXJJZCI6MH0.1GTQ9Z8USbhYf4p87pAaKEYZUJYyg8ehGGz6pQQzWM4

{
    "name": "Test Event",
    "description": "A test Evevnt",
    "location": "Test Location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}

##
POST http://localhost:8082/events
content-type: application/json

{
    "name": "Test Event 2",
    "description": "Another test Evevnt",
    "location": "Test Location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}
