package routes

import (
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
	"michaelchlon.fr/api/models"
)

// * NOTE: Define a handler for the "/events" route (GET) -----------------------------
func getEvents(context *gin.Context) {
	events, err := models.GetAllEvents() // * NOTE: Retrieve all events from the model
	if err != nil {
		context.JSON(http.StatusInternalServerError, gin.H{"message": "Could not fetch events!"})
		return
	}
	context.JSON(http.StatusOK, events) // * NOTE: Respond with a JSON object containing a message
}

// * NOTE: Define a handler for the "/events/:id" route (GET) ------------------------
func getEvent(context *gin.Context) {
	eventId, err := strconv.ParseInt(context.Param("id"), 10, 64) // * NOTE: Get the event ID from the URL parameters
	if err != nil {
		context.JSON(http.StatusBadRequest, gin.H{"message": "Invalid event ID!"}) // * NOTE: Respond with an error if the ID is invalid
		return
	}

	event, err := models.GetEventByID(eventId) // * NOTE: Retrieve the event by ID from the model
	if err != nil {
		context.JSON(http.StatusInternalServerError, gin.H{"message": "Could not fetch event!"}) // * NOTE: Respond with an error if the event could not be fetched
		return
	}

	context.JSON(http.StatusOK, event) // * NOTE: Respond with the event data in JSON format
}

// * NOTE: Define a handler for the "/events" route (POST) -----------------------------
func createEvent(context *gin.Context) {
	var event models.Event // * NOTE: Create a new event instance

	// * NOTE: Bind the JSON request body to the event instance
	if err := context.ShouldBindJSON(&event); err != nil {
		context.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	event.ID = 1     // * NOTE: Set a default ID for the event (in a real application, this would be generated by the database)
	event.UserID = 1 // * NOTE: Set a default UserID for the event (in a real application, this would be set based on the authenticated user)

	err := event.Save() // * NOTE: Save the event using the Save method defined in the model
	if err != nil {
		context.JSON(http.StatusInternalServerError, gin.H{"message": "Could not create event!"})
		return
	}

	context.JSON(http.StatusCreated, gin.H{
		"message": "Event created successfully!",
		"event":   event,
	}) // * NOTE: Respond with a success message
}
